def solucion_de_ecuanciones_lineales ():
    print("--->solucion de ecuanciones lineales\n")
    x=input("ingrese un numero para la X: ")
    x=int(x)
    a=(20-(7*x))
    b=(((-7+x)+2)-(10*x)+5)
    c=(((4*x)+4)+(9*x)+18)
    d=(((6*x)-5)+(8*x)+2)
    e=(((5*x)+78)/28)
    f=((((6*x)-7)/4)+((3*x)-5/7))
    a=int(a)
    b=int(b)
    c=int(c)
    d=int(d)
    e=int(e)
    f=int(f)
    print ("este es resultado de esta ecuación:","A",a,",","B",b,",","C",c,"\n","D",d, ",","E",e,",","F",f)
    ir_almenu=input("presine (c) para regresar al menú: ")
